#pragma once

// Generated by vkfu_gen from vk.xml (VK_HEADER_VERSION 42). Do not edit.

#include <algorithm>
#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <expected>
#include <iterator>
#include <memory>
#include <new>
#include <span>
#include <type_traits>

#include <vulkan/vulkan.h>

#include "../../../include/vkfu/branch_pipe.h"
#include "../../../include/vkfu/chain.h"
#include "../../../include/vkfu/expression.h"
#include "../../../include/vkfu/extension.h"
#include "../../../include/vkfu/query.h"
#include "../../../include/vkfu/reference.h"
#include "../../../include/vkfu/storage.h"
#include "../../../include/vkfu/vulkan_object.h"

constexpr auto _vkfu_address(VkWidgetColourInfoEXT& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetColourInfoEXT& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetColourInfoEXT const& value) noexcept -> VkWidgetColourInfoEXT
{
	return value;
}

constexpr auto _vkfu_address(VkWidgetCreateInfo& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetCreateInfo& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetCreateInfo const& value) noexcept -> VkWidgetCreateInfo
{
	return value;
}

constexpr auto _vkfu_address(VkWidgetLabelInfoKHR& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetLabelInfoKHR& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetLabelInfoKHR const& value) noexcept -> VkWidgetLabelInfoKHR
{
	return value;
}

constexpr auto _vkfu_address(VkWidgetLimits& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetLimits& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetLimits const& value) noexcept -> VkWidgetLimits
{
	return value;
}

constexpr auto _vkfu_address(VkWidgetPart& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetPart& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetPart const& value) noexcept -> VkWidgetPart
{
	return value;
}

constexpr auto _vkfu_address(VkWidgetTuning& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetTuning& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetTuning const& value) noexcept -> VkWidgetTuning
{
	return value;
}

#if defined(VK_USE_PLATFORM_WIN32_KHR)
constexpr auto _vkfu_address(VkWidgetWin32InfoKHR& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetWin32InfoKHR& value, void const* next) noexcept
{
	value.pNext = next;
}

constexpr auto _vkfu_evaluate(VkWidgetWin32InfoKHR const& value) noexcept -> VkWidgetWin32InfoKHR
{
	return value;
}
#endif

constexpr auto _vkfu_address(VkWidgetDriverPropertiesEXT& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetDriverPropertiesEXT& value, void const* next) noexcept
{
	value.pNext = const_cast<void*>(next);
}

constexpr auto _vkfu_evaluate(VkWidgetDriverPropertiesEXT const& value) noexcept -> VkWidgetDriverPropertiesEXT
{
	return value;
}

constexpr auto _vkfu_address(VkWidgetProperties& value) noexcept -> void const*
{
	return ::std::addressof(value);
}

constexpr void _vkfu_set_next(VkWidgetProperties& value, void const* next) noexcept
{
	value.pNext = const_cast<void*>(next);
}

constexpr auto _vkfu_evaluate(VkWidgetProperties const& value) noexcept -> VkWidgetProperties
{
	return value;
}

namespace vkfu::obj
{
struct widget{};
struct widget_part{};
struct widget_tuning{};
namespace khr
{
#if defined(VK_USE_PLATFORM_WIN32_KHR)
struct widget_win32{};
#endif
}
namespace option
{
struct widget_limits{};
}
namespace option::ext
{
struct widget_colour{};
}
namespace option::khr
{
struct widget_label{};
}
namespace result
{
struct widget_properties{};
}
namespace result::ext
{
struct widget_driver_properties{};
}
}

namespace vkfu
{
template<>
struct vulkan_object_trait<obj::option::ext::widget_colour>
{
	constexpr static auto root = false;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = false;
};

template<>
struct vulkan_object_trait<obj::widget>
{
	constexpr static auto root = true;
	constexpr static auto branch = true;
	constexpr static auto allow_duplicate = false;
};

template<>
struct vulkan_object_trait<obj::option::khr::widget_label>
{
	constexpr static auto root = false;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = true;
};

template<>
struct vulkan_object_trait<obj::option::widget_limits>
{
	constexpr static auto root = false;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = false;
};

template<>
struct vulkan_object_trait<obj::widget_part>
{
	constexpr static auto root = true;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = false;
};

template<>
struct vulkan_object_trait<obj::widget_tuning>
{
	constexpr static auto root = false;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = false;
};

#if defined(VK_USE_PLATFORM_WIN32_KHR)
template<>
struct vulkan_object_trait<obj::khr::widget_win32>
{
	constexpr static auto root = true;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = false;
};
#endif

template<>
struct vulkan_object_trait<obj::result::ext::widget_driver_properties>
{
	constexpr static auto root = false;
	constexpr static auto branch = false;
	constexpr static auto allow_duplicate = false;
};

template<>
struct vulkan_object_trait<obj::result::widget_properties>
{
	constexpr static auto root = true;
	constexpr static auto branch = true;
	constexpr static auto allow_duplicate = false;
};

template<>
struct expression_vulkan_tag<VkWidgetColourInfoEXT>
{
	using type = obj::option::ext::widget_colour;
};

template<>
struct vulkan_object_native<obj::option::ext::widget_colour>
{
	using type = VkWidgetColourInfoEXT;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_COLOUR_INFO_EXT;
};

template<>
struct expression_vulkan_tag<VkWidgetCreateInfo>
{
	using type = obj::widget;
};

template<>
struct vulkan_object_native<obj::widget>
{
	using type = VkWidgetCreateInfo;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_CREATE_INFO;
};

template<>
struct expression_vulkan_tag<VkWidgetLabelInfoKHR>
{
	using type = obj::option::khr::widget_label;
};

template<>
struct vulkan_object_native<obj::option::khr::widget_label>
{
	using type = VkWidgetLabelInfoKHR;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_LABEL_INFO_KHR;
};

template<>
struct expression_vulkan_tag<VkWidgetLimits>
{
	using type = obj::option::widget_limits;
};

template<>
struct vulkan_object_native<obj::option::widget_limits>
{
	using type = VkWidgetLimits;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_LIMITS;
};

template<>
struct expression_vulkan_tag<VkWidgetPart>
{
	using type = obj::widget_part;
};

template<>
struct vulkan_object_native<obj::widget_part>
{
	using type = VkWidgetPart;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_PART;
};

template<>
struct expression_vulkan_tag<VkWidgetTuning>
{
	using type = obj::widget_tuning;
};

template<>
struct vulkan_object_native<obj::widget_tuning>
{
	using type = VkWidgetTuning;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_TUNING;
};

#if defined(VK_USE_PLATFORM_WIN32_KHR)
template<>
struct expression_vulkan_tag<VkWidgetWin32InfoKHR>
{
	using type = obj::khr::widget_win32;
};

template<>
struct vulkan_object_native<obj::khr::widget_win32>
{
	using type = VkWidgetWin32InfoKHR;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_WIN32_INFO_KHR;
};
#endif

template<>
struct expression_vulkan_tag<VkWidgetDriverPropertiesEXT>
{
	using type = obj::result::ext::widget_driver_properties;
};

template<>
struct vulkan_object_native<obj::result::ext::widget_driver_properties>
{
	using type = VkWidgetDriverPropertiesEXT;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_DRIVER_PROPERTIES_EXT;
};

template<>
struct expression_vulkan_tag<VkWidgetProperties>
{
	using type = obj::result::widget_properties;
};

template<>
struct vulkan_object_native<obj::result::widget_properties>
{
	using type = VkWidgetProperties;
	constexpr static auto structure_type = VK_STRUCTURE_TYPE_WIDGET_PROPERTIES;
};

template<>
struct vulkan_object_extensions<obj::option::ext::widget_colour>
{
	constexpr static ::std::array<char const*, 1> names{"VK_EXT_widget_colour"};
	constexpr static ::std::uint32_t core = 0;
	constexpr static auto instance = false;
};

template<>
struct vulkan_object_extensions<obj::widget>
{
	constexpr static ::std::array<char const*, 0> names{};
	constexpr static ::std::uint32_t core = VK_API_VERSION_1_0;
	constexpr static auto instance = false;
};

template<>
struct vulkan_object_extensions<obj::option::khr::widget_label>
{
	constexpr static ::std::array<char const*, 1> names{"VK_KHR_widget_label"};
	constexpr static ::std::uint32_t core = 0;
	constexpr static auto instance = false;
};

template<>
struct vulkan_object_extensions<obj::option::widget_limits>
{
	constexpr static ::std::array<char const*, 1> names{"VK_KHR_widget_limits"};
	constexpr static ::std::uint32_t core = VK_API_VERSION_1_1;
	constexpr static auto instance = false;
};

template<>
struct vulkan_object_extensions<obj::widget_part>
{
	constexpr static ::std::array<char const*, 0> names{};
	constexpr static ::std::uint32_t core = VK_API_VERSION_1_0;
	constexpr static auto instance = false;
};

template<>
struct vulkan_object_extensions<obj::widget_tuning>
{
	constexpr static ::std::array<char const*, 0> names{};
	constexpr static ::std::uint32_t core = VK_API_VERSION_1_0;
	constexpr static auto instance = false;
};

#if defined(VK_USE_PLATFORM_WIN32_KHR)
template<>
struct vulkan_object_extensions<obj::khr::widget_win32>
{
	constexpr static ::std::array<char const*, 1> names{"VK_KHR_widget_win32"};
	constexpr static ::std::uint32_t core = 0;
	constexpr static auto instance = true;
};
#endif

template<>
struct vulkan_object_extensions<obj::result::ext::widget_driver_properties>
{
	constexpr static ::std::array<char const*, 1> names{"VK_EXT_widget_colour"};
	constexpr static ::std::uint32_t core = 0;
	constexpr static auto instance = false;
};

template<>
struct vulkan_object_extensions<obj::result::widget_properties>
{
	constexpr static ::std::array<char const*, 0> names{};
	constexpr static ::std::uint32_t core = VK_API_VERSION_1_0;
	constexpr static auto instance = false;
};

template<>
inline constexpr auto is_vulkan_object_compatible_with_v<obj::widget, obj::option::ext::widget_colour> = true;
template<>
inline constexpr auto is_vulkan_object_compatible_with_v<obj::widget, obj::option::khr::widget_label> = true;
template<>
inline constexpr auto is_vulkan_object_compatible_with_v<obj::widget, obj::option::widget_limits> = true;
#if defined(VK_USE_PLATFORM_WIN32_KHR)
template<>
inline constexpr auto is_vulkan_object_compatible_with_v<obj::widget, obj::khr::widget_win32> = true;
#endif
template<>
inline constexpr auto is_vulkan_object_compatible_with_v<obj::result::widget_properties, obj::result::ext::widget_driver_properties> = true;
}

namespace vkfu::obj
{
namespace option::khr
{
using widget_limits = ::vkfu::obj::option::widget_limits;
}
}
namespace vkfu::enums
{
enum class widget_mode : ::std::underlying_type_t<VkWidgetMode>
{
	plain = VK_WIDGET_MODE_PLAIN,
	fancy = VK_WIDGET_MODE_FANCY,
};

}


namespace vkfu::param
{
using ::vkfu::operator|;

template<::vkfu::reference_expression_for<obj::widget_tuning> tuning_expression = ::vkfu::absent_expression>
struct widget
{
	using vulkan_tag_type = obj::widget;
	using storage_type = ::vkfu::reference_storage<VkWidgetCreateInfo
		, ::vkfu::reference_slot<&VkWidgetCreateInfo::pTuning, ::vkfu::reference_storage_of_t<tuning_expression>>
		>;

	struct flags_type
	{
		VkWidgetFlags alpha : 1 = 0;
		VkWidgetFlags _reserved_1 : 1 = 0;
		VkWidgetFlags gamma : 1 = 0;
		VkWidgetFlags _reserved_3 : 29 = 0;
	};

	flags_type flags{};
	::vkfu::enums::widget_mode mode{};
	bool enable_tracing = false;
	::std::span<VkWidgetPart const> parts{};
	tuning_expression tuning{};
	VkExtent extent{};
	::std::array<float, 4> weights{};

	constexpr auto evaluate() -> storage_type
	{
		auto value = VkWidgetCreateInfo{
			.sType = VK_STRUCTURE_TYPE_WIDGET_CREATE_INFO,
			.pNext = nullptr,
			.flags = ::std::bit_cast<VkWidgetFlags>(flags),
			.mode = static_cast<VkWidgetMode>(mode),
			.enableTracing = enable_tracing ? VK_TRUE : VK_FALSE,
			.partCount = static_cast<::std::uint32_t>(parts.size()),
			.pParts = parts.data(),
			.pTuning = nullptr,
			.extent = extent,
			.weights = {},
		};
		::std::ranges::copy(weights, value.weights);
		return storage_type{
			value,
			::vkfu::evaluate(tuning),
		};
	}
};

static_assert(sizeof(widget<>::flags_type) == sizeof(VkWidgetFlags));
#if !defined(__clang__)
static_assert(::std::bit_cast<VkWidgetFlags>(widget<>::flags_type{.alpha = 1}) == VK_WIDGET_ALPHA_BIT);
static_assert(::std::bit_cast<VkWidgetFlags>(widget<>::flags_type{.gamma = 1}) == VK_WIDGET_GAMMA_BIT);
#endif

struct widget_part
{
	using vulkan_tag_type = obj::widget_part;

	::std::uint32_t index{};

	constexpr auto evaluate() const noexcept -> VkWidgetPart
	{
		return VkWidgetPart{
			.sType = VK_STRUCTURE_TYPE_WIDGET_PART,
			.pNext = nullptr,
			.index = index,
		};
	}
};

struct widget_tuning
{
	using vulkan_tag_type = obj::widget_tuning;

	float bias{};

	constexpr auto evaluate() const noexcept -> VkWidgetTuning
	{
		return VkWidgetTuning{
			.sType = VK_STRUCTURE_TYPE_WIDGET_TUNING,
			.pNext = nullptr,
			.bias = bias,
		};
	}
};

namespace khr
{
using ::vkfu::operator|;

#if defined(VK_USE_PLATFORM_WIN32_KHR)
struct widget_win32
{
	using vulkan_tag_type = obj::khr::widget_win32;

	void* handle = nullptr;

	constexpr auto evaluate() const noexcept -> VkWidgetWin32InfoKHR
	{
		return VkWidgetWin32InfoKHR{
			.sType = VK_STRUCTURE_TYPE_WIDGET_WIN32_INFO_KHR,
			.pNext = nullptr,
			.handle = handle,
		};
	}
};
#endif

}

namespace option
{
using ::vkfu::operator|;

struct widget_limits
{
	using vulkan_tag_type = obj::option::widget_limits;

	::std::uint32_t max_parts{};

	constexpr auto evaluate() const noexcept -> VkWidgetLimits
	{
		return VkWidgetLimits{
			.sType = VK_STRUCTURE_TYPE_WIDGET_LIMITS,
			.pNext = nullptr,
			.maxParts = max_parts,
		};
	}
};

}

namespace option::ext
{
using ::vkfu::operator|;

struct widget_colour
{
	using vulkan_tag_type = obj::option::ext::widget_colour;

	::vkfu::enums::widget_mode fallback_mode{};

	constexpr auto evaluate() const noexcept -> VkWidgetColourInfoEXT
	{
		return VkWidgetColourInfoEXT{
			.sType = VK_STRUCTURE_TYPE_WIDGET_COLOUR_INFO_EXT,
			.pNext = nullptr,
			.fallbackMode = static_cast<VkWidgetMode>(fallback_mode),
		};
	}
};

}

namespace option::khr
{
using ::vkfu::operator|;

struct widget_label
{
	using vulkan_tag_type = obj::option::khr::widget_label;

	::std::uint32_t tag{};

	constexpr auto evaluate() const noexcept -> VkWidgetLabelInfoKHR
	{
		return VkWidgetLabelInfoKHR{
			.sType = VK_STRUCTURE_TYPE_WIDGET_LABEL_INFO_KHR,
			.pNext = nullptr,
			.tag = tag,
		};
	}
};

}

struct extent
{
	::std::uint32_t width{};
	::std::uint32_t height{};

	constexpr auto evaluate() const noexcept -> VkExtent
	{
		return VkExtent{
			.width = width,
			.height = height,
		};
	}
};

namespace option::khr
{
using widget_limits = ::vkfu::param::option::widget_limits;
}

}
namespace vkfu
{
template<::vkfu::expression_for<::vkfu::obj::widget> Expression>
[[nodiscard]] auto create_widget(VkDevice device, Expression&& info, ::VkAllocationCallbacks const* allocation_callbacks, ::std::nothrow_t) noexcept
	-> ::std::expected<VkWidget, ::VkResult>
{
	decltype(auto) storage = ::vkfu::evaluate(::std::forward<Expression>(info));
	auto produced = VkWidget{};
	auto const result = ::vkCreateWidget(
		device, ::std::addressof(::vkfu::unpack(storage)), allocation_callbacks, ::std::addressof(produced));
	if (result != ::VK_SUCCESS)
	{
		return ::std::unexpected{result};
	}
	return produced;
}

template<::vkfu::expression_for<::vkfu::obj::widget> Expression>
[[nodiscard]] auto create_widget(VkDevice device, Expression&& info, ::VkAllocationCallbacks const* allocation_callbacks = nullptr) -> VkWidget
{
	auto produced = create_widget(device, ::std::forward<Expression>(info), allocation_callbacks, ::std::nothrow);
	if (!produced)
	{
		throw produced.error();
	}
	return *produced;
}

#if defined(VK_USE_PLATFORM_WIN32_KHR)
template<::vkfu::expression_for<::vkfu::obj::khr::widget_win32> Expression1>
void cmd_set_win32_widget(VkRecorder recorder, Expression1&& info)
{
	decltype(auto) storage1 = ::vkfu::evaluate(::std::forward<Expression1>(info));
	::vkCmdSetWin32Widget(recorder, ::std::addressof(::vkfu::unpack(storage1)));
}
#endif

inline void cmd_submit_parts(VkRecorder recorder, ::std::span<VkWidgetPart const> parts)
{
	::vkCmdSubmitParts(recorder, static_cast<::std::uint32_t>(parts.size()), parts.data());
}

[[nodiscard]] inline auto count_widget_reports(VkDevice device, ::std::nothrow_t) noexcept
	-> ::std::expected<::std::uint32_t, ::VkResult>
{
	auto count = ::std::uint32_t{};
	if (auto const outcome = ::vkEnumerateWidgetReports(device, ::std::addressof(count), nullptr); outcome != ::VK_SUCCESS)
	{
		return ::std::unexpected{outcome};
	}
	return count;
}

[[nodiscard]] inline auto count_widget_reports(VkDevice device) -> ::std::uint32_t
{
	auto const outcome = count_widget_reports(device, ::std::nothrow);
	if (!outcome)
	{
		throw outcome.error();
	}
	return *outcome;
}

[[nodiscard]] inline auto enumerate_widget_reports(VkDevice device, ::std::span<VkWidgetReport> out, ::std::nothrow_t) noexcept
	-> ::std::expected<::std::span<VkWidgetReport>, ::VkResult>
{
	auto count = static_cast<::std::uint32_t>(out.size());
	auto const outcome = ::vkEnumerateWidgetReports(device, ::std::addressof(count), out.data());
	if (outcome != ::VK_SUCCESS && outcome != ::VK_INCOMPLETE)
	{
		return ::std::unexpected{outcome};
	}
	return out.first(count);
}

[[nodiscard]] inline auto enumerate_widget_reports(VkDevice device, ::std::span<VkWidgetReport> out) -> ::std::span<VkWidgetReport>
{
	auto const outcome = enumerate_widget_reports(device, out, ::std::nothrow);
	if (!outcome)
	{
		throw outcome.error();
	}
	return *outcome;
}

template<::std::contiguous_iterator Out>
	requires ::std::same_as<::std::iter_value_t<Out>, VkWidgetReport>
[[nodiscard]] auto enumerate_widget_reports(VkDevice device, Out out) -> Out
{
	auto const count = count_widget_reports(device);
	auto const written = enumerate_widget_reports(device, ::std::span<VkWidgetReport>{::std::to_address(out), count});
	return out + static_cast<::std::iter_difference_t<Out>>(written.size());
}

template<::vkfu::query_extension_of<::vkfu::obj::result::widget_properties>... Extras>
[[nodiscard]] auto get_widget_properties(VkDevice device) -> ::vkfu::query_chain<::vkfu::obj::result::widget_properties, Extras...>
{
	auto chain = ::vkfu::query_chain<::vkfu::obj::result::widget_properties, Extras...>{};
	::vkGetWidgetProperties(device, ::std::addressof(chain.head()));
	return chain;
}

}
